spring.application.name=MiBanco Perú

spring.datasource.url=jdbc:mysql://reseau.proxy.rlwy.net:50388/railway?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=kEcUUvZvlXYxjZduUMeWECebNqrInZqz

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

server.port=${PORT:8080}

spring.jackson.time-zone=America/Lima

logging.level.com.mibanco=INFO
logging.level.org.springframework.security=WARN
